import { Track } from '../../engine/track.ts'
import type { Provenance } from '../../evidence/evidence.ts'
import type { LngLat } from '../../geo/geodesy.ts'
import { allocate, megatons, type Launcher, type Target } from '../../models/allocation.ts'
import { ATTRITION_MODEL, calibrate, DEFAULT_RELIABILITY, DOCUMENTED_ASSURANCE, RELIABILITY } from '../../models/attrition.ts'
import { BLAST_MODEL, promptEffects } from '../../models/blast.ts'
import { enactStrike } from '../strike.ts'
import { generationAt, optionHours, SYSTEMS } from '../../models/readiness.ts'
import type { Entity, Study, StudyEvent } from '../study.ts'
import orderOfBattle from '../../../data/siop62/order-of-battle-1961.json'
import targetFile from '../../../data/siop62/targets-1956-priority.json'
import airfieldFile from '../../../data/siop62/airfields-1956-priority.json'
import sovietFile from '../../../data/siop62/soviet-response-1961.json'
import { haversineMetres } from '../../geo/geodesy.ts'

/**
 * SIOP//62 enactment by execution option. Option 1 is the alert force: the
 * 1,004 delivery systems and about 1,685 weapons that could launch on fifteen
 * minutes' warning. Options 2 to 14 add the force generated by up to fourteen
 * hours of preparation, to the fully generated 3,267 weapons of Table 3. All
 * of it flies from the documented order of battle of mid-1961 to the 1956
 * study's highest-priority complexes. The launchers and the totals are
 * documented; the strengths on each base are reconstructed by stated rules;
 * every assignment of a weapon to a target is inferred.
 */
const SAGAN: Provenance = { source: 'Sagan 1987', locator: 'briefing pp. 48–49; Table 1, 15 July 1961', url: 'https://archive.org/details/SIOP62TheNuclearWarPlanBriefingToPresidentKennedy' }
const EBB798: Provenance = { source: 'National Security Archive EBB 798', locator: '1961 estimate: 80 million Soviet dead from the alert force', url: 'https://nsarchive.gwu.edu/briefing-book/nuclear-vault/2022-07-14/long-classified-us-estimates-nuclear-war-casualties-during' }

interface RawLauncher {
  id: string
  name: string
  kind: string
  lon: number
  lat: number
  wing?: string
  note?: string
  aircraft?: number
  weapons?: number
  yieldKt?: number
  evidence: string
  positionEvidence: string
  source: string
  geocoded?: string
}

const REACTION_FIXED = 15 * 60
const REACTION_SEA = 2 * 3_600
const B52_MS = 845_000 / 3_600
const B47_MS = 800_000 / 3_600
const TACTICAL_MS = 900_000 / 3_600
const MACE_MS = 1_040_000 / 3_600

/** Documented megatonnage of the fully generated force (Sagan n. 8), against which the Mk-28 assumption falls short. */
const GENERATED_MEGATONS = 7_420
/** Documented SAC aircraft weapons on alert, 15 July 1961; the bomber bases are scaled to carry it. */
const SAC_AIRCRAFT_WEAPONS_ON_ALERT = 1_212
/**
 * Generation rules per system, alert to fully generated (Table 1 to Table 3,
 * 15 July 1961, with Sagan p. 29 for the missiles): 24 of 78 ICBMs on alert,
 * two of five Polaris boats on station, the Jupiters already on alert. With
 * the bomber bases at full strength these give 3,267 weapons at option 14,
 * the documented total, and 188 ballistic missiles, Table 3's figure exactly.
 */
const GENERATION = {
  icbmTotal: 78,
  icbmAlert: 24,
  polarisBoats: 5,
  polarisAlertBoats: 2,
  aircraftGenerated: SYSTEMS.find((r) => r.system === 'Aircraft')!.generated,
  cruise: SYSTEMS.find((r) => r.system === 'Cruise missiles')!,
  provenance: { source: 'Sagan 1987', locator: 'Tables 1 and 3, 15 July 1961; p. 29 for the missile alert rates' } as Provenance,
}

/**
 * Air-refuelling areas, from the Chrome Dome record: KC-135s "operating out
 * of bases in the northeast United States, Alaska, and Spain", the BLACK
 * GOAT track over Newfoundland, and a Pacific refuelling on the western
 * route (Wikipedia, Operation Chrome Dome). A bomber leaving North America
 * for the bloc routes through the area that adds least to its great circle
 * and holds there ten minutes. Reconstructed: the areas are documented, the
 * choice per sortie is not.
 */
const REFUEL_AREAS: Array<{ id: string; name: string; position: LngLat }> = [
  { id: 'newfoundland', name: 'BLACK GOAT · Newfoundland', position: [-56.0, 49.5] },
  { id: 'alaska', name: 'Alaska', position: [-150.0, 66.0] },
  { id: 'spain', name: 'Spain', position: [-4.0, 39.5] },
  { id: 'pacific', name: 'Pacific', position: [-142.0, 57.0] },
]
const REFUEL_HOLD_SECONDS = 10 * 60

/** Bombers based in North America refuel en route; those already forward do not. */
function refuelVia(from: LngLat, to: LngLat): { area: (typeof REFUEL_AREAS)[number]; extraMetres: number } | null {
  if (from[0] > -30 && from[0] < 100) return null
  const direct = haversineMetres(from, to)
  let best: { area: (typeof REFUEL_AREAS)[number]; extraMetres: number } | null = null
  for (const area of REFUEL_AREAS) {
    const extra = haversineMetres(from, area.position) + haversineMetres(area.position, to) - direct
    if (!best || extra < best.extraMetres) best = { area, extraMetres: extra }
  }
  return best
}

/** Generation state of the force for an option: 0 is the alert force, 1 the fully generated force. */
export interface ForceGeneration {
  option: number
  hours: number
  /** Fraction of the way from the alert tables to the generated tables; straight line, as the readiness lab draws it. */
  fraction: number
}

export function forceGeneration(option: number): ForceGeneration {
  const hours = optionHours(option)
  return { option, hours, fraction: hours / 14 }
}

/** How each launcher's weapons grow from alert to generated, for the provenance panel. */
export interface LauncherGeneration {
  alert: number
  generated: number
  rule: string
}

function buildLaunchers(generation: ForceGeneration): { launchers: Launcher[]; alertFraction: number; bomberWeaponsNominal: number; growth: Record<string, LauncherGeneration> } {
  const raw = (orderOfBattle as { launchers: RawLauncher[] }).launchers
  const bombers = raw.filter((l) => l.kind === 'b52' || l.kind === 'b52h' || l.kind === 'b47' || l.kind === 'b47r')
  const nominal = bombers.reduce((s, l) => s + (l.aircraft ?? 0) * (l.kind.startsWith('b52') ? 2 : 1), 0)
  const sacNominal = bombers.filter((l) => l.kind !== 'b47r').reduce((s, l) => s + (l.aircraft ?? 0) * (l.kind.startsWith('b52') ? 2 : 1), 0)
  const alertFraction = SAC_AIRCRAFT_WEAPONS_ON_ALERT / sacNominal
  // Theatre aircraft take what remains of Table 3's aircraft weapons once every SAC bomber is generated.
  const tacticalAlert = raw.filter((l) => l.kind === 'tactical').reduce((s, l) => s + (l.weapons ?? 0), 0)
  const tacticalGenerated = GENERATION.aircraftGenerated - nominal
  const f = generation.fraction
  const at = (alert: number, generated: number) => alert + f * (generated - alert)
  const launchers: Launcher[] = []
  const growth: Record<string, LauncherGeneration> = {}
  const exact: Record<string, number> = {}
  const push = (launcher: Launcher, alert: number, generated: number, rule: string) => {
    launchers.push(launcher)
    exact[launcher.id] = launcher.weapons
    growth[launcher.id] = { alert, generated, rule }
  }
  for (const l of raw) {
    const position: LngLat = [l.lon, l.lat]
    if (l.kind === 'b52' || l.kind === 'b52h' || l.kind === 'b47' || l.kind === 'b47r') {
      const wpv = l.kind.startsWith('b52') ? 2 : 1
      const generated = (l.aircraft ?? 0) * wpv
      const alert = generated * alertFraction
      push(
        { id: l.id, name: l.name, kind: 'bomber', position, weapons: at(alert, generated), weaponsPerVehicle: wpv, rangeMetres: l.kind === 'b47r' ? 4_500_000 : Infinity, yieldKt: 1_100, reactionSeconds: REACTION_FIXED, speedMs: wpv === 2 ? B52_MS : B47_MS },
        alert,
        generated,
        `Base strength × ${wpv} weapons × alert fraction ${alertFraction.toFixed(2)} on alert, the fraction chosen so SAC bases carry the documented 1,212 aircraft weapons; every aircraft generated by fourteen hours`,
      )
    } else if (l.kind === 'icbm') {
      const alert = l.weapons ?? 0
      const generated = (alert * GENERATION.icbmTotal) / GENERATION.icbmAlert
      push({ id: l.id, name: l.name, kind: 'icbm', position, weapons: at(alert, generated), weaponsPerVehicle: 1, rangeMetres: 14_000_000, yieldKt: l.yieldKt ?? 1_440, reactionSeconds: REACTION_FIXED }, alert, generated, `Table 1 on alert; ${GENERATION.icbmAlert} of ${GENERATION.icbmTotal} ICBMs were on alert (Sagan p. 29), so the site generates to ${(GENERATION.icbmTotal / GENERATION.icbmAlert).toFixed(2)} times its alert strength`)
    } else if (l.kind === 'irbm') {
      const alert = l.weapons ?? 0
      push({ id: l.id, name: l.name, kind: 'irbm', position, weapons: alert, weaponsPerVehicle: 1, rangeMetres: 2_400_000, yieldKt: l.yieldKt ?? 1_440, reactionSeconds: REACTION_FIXED }, alert, alert, 'Table 1; the Jupiters stood on alert, so generation adds none')
    } else if (l.kind === 'slbm') {
      const alert = l.weapons ?? 0
      const generated = (alert * GENERATION.polarisBoats) / GENERATION.polarisAlertBoats
      push({ id: l.id, name: l.name, kind: 'slbm', position, weapons: at(alert, generated), weaponsPerVehicle: 1, rangeMetres: 2_200_000, yieldKt: l.yieldKt ?? 600, reactionSeconds: REACTION_SEA }, alert, generated, `Two of five Polaris boats on station (Sagan p. 29); all five with strategic warning`)
    } else if (l.kind === 'tactical') {
      const alert = l.weapons ?? 0
      const generated = (alert * tacticalGenerated) / tacticalAlert
      push({ id: l.id, name: l.name, kind: 'bomber', position, weapons: at(alert, generated), weaponsPerVehicle: 1, rangeMetres: 1_800_000, yieldKt: l.yieldKt ?? 70, reactionSeconds: REACTION_FIXED, speedMs: TACTICAL_MS }, alert, generated, `Theatre share of Table 1 on alert; the ${tacticalGenerated} aircraft weapons Table 3 leaves once every SAC bomber is generated, in proportion`)
    } else if (l.kind === 'cruise') {
      const alert = l.weapons ?? 0
      const generated = (alert * GENERATION.cruise.generated) / GENERATION.cruise.alert
      push({ id: l.id, name: l.name, kind: 'bomber', position, weapons: at(alert, generated), weaponsPerVehicle: 1, rangeMetres: 2_000_000, yieldKt: l.yieldKt ?? 1_100, reactionSeconds: REACTION_FIXED, speedMs: MACE_MS }, alert, generated, `Table 1 on alert; Table 3's ${GENERATION.cruise.generated} cruise missiles against ${GENERATION.cruise.alert} on alert, in proportion`)
    }
  }
  // Round per raw kind so that each group's total is the rounded group total, not the sum of roundings.
  for (const kind of new Set(raw.map((l) => l.kind))) {
    const group = launchers.filter((l) => raw.find((r) => r.id === l.id)?.kind === kind)
    const rounded = roundPreservingSum(group.map((l) => exact[l.id]))
    group.forEach((l, i) => (l.weapons = rounded[i]))
  }
  return { launchers, alertFraction, bomberWeaponsNominal: nominal, growth }
}

/** Largest-remainder rounding: integers whose sum is the rounded sum of the inputs. */
export function roundPreservingSum(values: number[]): number[] {
  const floors = values.map((v) => Math.floor(v))
  let short = Math.round(values.reduce((a, b) => a + b, 0)) - floors.reduce((a, b) => a + b, 0)
  const order = values.map((v, i) => ({ i, r: v - floors[i] })).sort((a, b) => b.r - a.r)
  for (const { i } of order) {
    if (short <= 0) break
    floors[i] += 1
    short -= 1
  }
  return floors
}

/** Priority offset that places every complex after every airfield: the study's first task is the Air Power Battle. */
const COMPLEX_AFTER_AIRFIELDS = 10_000

export interface TargetMeta {
  kind: 'airfield' | 'complex'
  categories?: string[]
}
export const TARGET_META: Record<string, TargetMeta> = {}

function buildTargets(): Target[] {
  const airfields = (airfieldFile as { targets: Array<{ be: string; priority: number; name: string; lat: number; lon: number }> }).targets.map((a) => {
    TARGET_META[`a-${a.be}`] = { kind: 'airfield' }
    return { id: `a-${a.be}`, name: a.name, priority: a.priority, position: [a.lon, a.lat] as LngLat }
  })
  const complexes = (targetFile as { targets: Array<{ complex: string; priority: number; name: string; lat: number; lon: number; categoryNames?: string[] }> }).targets.map((t) => {
    TARGET_META[`t-${t.complex}`] = { kind: 'complex', categories: t.categoryNames }
    return { id: `t-${t.complex}`, name: t.name, priority: t.priority + COMPLEX_AFTER_AIRFIELDS, position: [t.lon, t.lat] as LngLat }
  })
  return [...airfields, ...complexes]
}

export interface AlertForceSummary {
  option: number
  preparationHours: number
  weaponsPerTarget: number
  firstDetonation: number
  lastDetonation: number
  launchers: number
  weapons: number
  delivered: number
  lostReliability: number
  lostPenetration: number
  penetration: number
  sorties: number
  targetsCovered: number
  airfieldsCovered: number
  complexesCovered: number
  megatons: number
  alertFraction: number
  bomberVehicles: number
}

function hash01Local(key: string): number {
  let h = 2166136261
  for (let i = 0; i < key.length; i += 1) {
    h ^= key.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return ((h >>> 0) % 1_000_003) / 1_000_003
}

function slerpTo(a: LngLat, b: LngLat, f: number): LngLat {
  const t = new Track([
    { position: a, time: 0 },
    { position: b, time: 1 },
  ])
  return t.positionAt(Math.max(0, Math.min(1, f))) ?? a
}

export function buildAlertForce(option = 1): { study: Study; summary: AlertForceSummary } {
  const generation = forceGeneration(option)
  const { launchers, alertFraction, growth } = buildLaunchers(generation)
  const targets = buildTargets()
  // The target list is the same for every option; a bigger force spreads over it: two weapons per target for the alert force, more as the force grows.
  const weaponsTotal = launchers.reduce((s, l) => s + l.weapons, 0)
  const weaponsPerTarget = Math.max(2, Math.ceil(weaponsTotal / targets.length))
  const optionName = option === 1 ? 'ALERT FORCE' : option === 14 ? 'STRATEGIC WARNING' : `${generation.hours} H PREPARATION`
  const targetById = Object.fromEntries(targets.map((t) => [t.id, t]))
  const raw = Object.fromEntries((orderOfBattle as { launchers: RawLauncher[] }).launchers.map((l) => [l.id, l]))

  const entities: Entity[] = []
  const events: StudyEvent[] = []

  // Launcher sites, labelled.
  for (const l of launchers) {
    if (l.weapons === 0) continue
    const r = raw[l.id]
    entities.push({
      kind: 'site',
      id: l.id,
      name: l.name,
      designation: `${l.kind.toUpperCase()} · ${l.weapons} WEAPONS ${option === 1 ? 'ON ALERT' : 'GENERATED'}`,
      // Only the missile and theatre sites are labelled at globe zoom; bomber bases keep their marks.
      label: l.kind !== 'bomber' || (r.kind !== 'b52' && r.kind !== 'b52h' && r.kind !== 'b47' && r.kind !== 'b47r'),
      position: l.position,
      evidence: r.evidence === 'documented' ? 'documented' : 'inferred',
      provenance: { source: r.source, method: r.wing ?? r.note },
      facts: [
        { label: option === 1 ? 'Weapons on alert' : `Weapons at option ${option}`, value: option === 1 ? String(l.weapons) : `${l.weapons} (${Math.round(growth[l.id].alert)} on alert, ${Math.round(growth[l.id].generated)} fully generated)`, evidence: r.evidence === 'documented' && l.kind !== 'bomber' && option === 1 ? 'documented' : 'reconstructed', provenance: { source: 'Rule', locator: GENERATION.provenance.locator, method: growth[l.id].rule } },
        { label: 'Position', value: r.geocoded ?? 'hand-set', evidence: r.positionEvidence as 'documented' | 'reconstructed' | 'inferred', provenance: { source: 'Modern map' } },
      ],
    })
  }

  // The strike, through the shared builder: allocation above, attrition calibrated to the documented assurance,
  // bombers from North America routed through the Chrome Dome refuelling areas, one effect per target.
  const strike = enactStrike({
    prefix: 'us',
    side: 'attacker',
    launchers,
    targets,
    allocation: { maxWeaponsPerTarget: weaponsPerTarget },
    attrition: (sorties) => {
      const c = calibrate(sorties, DOCUMENTED_ASSURANCE)
      return { reliability: DEFAULT_RELIABILITY, penetration: c.penetration, note: ATTRITION_MODEL }
    },
    allocationRule: { source: 'Allocation rule', method: 'Highest-priority targets first, nearest launcher in range, missiles before bombers; not a documented assignment' },
    vehicle: { evidence: 'inferred', provenance: { source: 'Order of battle of 15 July 1961', method: 'Base strengths by stated rule; every sortie inferred' } },
    route: { cruise: { source: 'Great circle at cruise speed' }, ballistic: { source: 'Minimum-energy trajectory' } },
    cruiseRoute: (l, t, launch, arrival) => {
      const refuel = (l.speedMs ?? 0) < 300 ? refuelVia(l.position, t.position) : null
      if (!refuel) return null
      const speed = l.speedMs ?? B52_MS
      const toArea = launch + haversineMetres(l.position, refuel.area.position) / speed
      return {
        waypoints: [
          { position: l.position, time: launch },
          { position: refuel.area.position, time: toArea },
          { position: refuel.area.position, time: toArea + REFUEL_HOLD_SECONDS },
          { position: t.position, time: arrival + refuel.extraMetres / speed + REFUEL_HOLD_SECONDS },
        ],
        provenance: { source: `Great circle at cruise speed via the ${refuel.area.name} refuelling area, ten-minute hold` },
      }
    },
    targetCategory: (t) => `${TARGET_META[t.id]?.kind === 'airfield' ? 'AIRFIELD' : 'COMPLEX'} · PRIORITY ${t.priority % COMPLEX_AFTER_AIRFIELDS}`,
    targetFacts: (t) => [
      { label: '1956 priority', value: `${t.priority % COMPLEX_AFTER_AIRFIELDS} on the ${TARGET_META[t.id]?.kind === 'airfield' ? 'airfield' : 'complex'} list`, evidence: 'documented', provenance: { source: TARGET_META[t.id]?.kind === 'airfield' ? 'SAC AWRS 1959 (June 1956), airfield list, section 6' : 'SAC AWRS 1959 (June 1956), city list' } },
      ...(TARGET_META[t.id]?.categories?.length ? [{ label: 'Categories', value: TARGET_META[t.id].categories!.join(' · '), evidence: 'documented' as const, provenance: { source: 'Category code list, section 3' } }] : []),
    ],
  })
  entities.push(...strike.entities)
  const result = { sorties: strike.sorties, weaponsAssigned: strike.summary.weapons, targetsCovered: strike.summary.targetsCovered }
  const firstArrival = strike.firstArrival
  const { delivered, lostReliability, lostPenetration } = strike.summary
  const calibration = { penetration: strike.summary.penetration }

  // The Soviet response: documented force levels, inferred bases and targets, coupled to the strikes above.
  const soviet = sovietFile as typeof sovietFile
  const sovietSummary = { launched: 0, delivered: 0, destroyedOnGround: 0, lost: 0 }
  {
    const doc = soviet.documented
    const inf = soviet.inferred
    const bombersTotal = doc.bombersOverNorthAmerica.value
    const perBase = Math.round(bombersTotal / inf.bases.length)
    const alertFraction = doc.bomberGroundAlert.value
    const usTargets: Target[] = [
      ...launchers.filter((l) => l.weapons > 0 && (l.kind === 'icbm' || l.kind === 'irbm' || l.kind === 'bomber') && raw[l.id].kind !== 'tactical' && raw[l.id].kind !== 'cruise').map((l, i) => ({ id: `us-${l.id}`, name: l.name, priority: l.kind === 'icbm' ? i : 100 + i, position: l.position })),
      ...inf.cities1960.map((c, i) => ({ id: `us-city-${i}`, name: c.name, priority: 50 + i, position: [c.lon, c.lat] as LngLat })),
    ]
    // Delivered US detonations by time, to decide which Soviet bases are struck before they can generate.
    const usStrikes = Object.entries(firstArrival).map(([id, fa]) => ({ position: targetById[id].position, time: fa.time }))
    const sovietLaunchers: Launcher[] = []
    const sovietSites: Entity[] = []
    for (const b of inf.bases) {
      const position: LngLat = [b.lon, b.lat]
      const struckAt = usStrikes.filter((st) => haversineMetres(st.position, position) < 30_000).map((st) => st.time).sort((p, q) => p - q)[0]
      const generationTime = inf.generationHours * 3_600
      const alertBombers = Math.round(perBase * alertFraction)
      const nonAlertSurvive = struckAt === undefined || struckAt > generationTime
      const bombers = alertBombers + (nonAlertSurvive ? perBase - alertBombers : 0)
      sovietSummary.destroyedOnGround += nonAlertSurvive ? 0 : perBase - alertBombers
      sovietLaunchers.push({ id: `sov-${b.id}`, name: b.name, kind: 'bomber', position, weapons: bombers, weaponsPerVehicle: 1, rangeMetres: inf.bomberRangeKm * 1_000, yieldKt: inf.bomberYieldKt.value, reactionSeconds: inf.launchOnWarningMinutes * 60, speedMs: (inf.bomberSpeedKmh * 1_000) / 3_600 })
      sovietSites.push({
        kind: 'site',
        id: `sov-${b.id}`,
        name: b.name,
        designation: `LONG RANGE AVIATION · ${perBase} BOMBERS · ${alertBombers} ON ALERT${nonAlertSurvive ? '' : ` · STRUCK AT H+${Math.round((struckAt ?? 0) / 60)} MIN`}`,
        position,
        evidence: 'inferred',
        provenance: { source: b.source, method: `Bombers per base: ${bombersTotal} that could reach North America (documented) spread over ${inf.bases.length} inferred bases` },
        facts: [
          { label: 'On ground alert', value: `${Math.round(alertFraction * 100)}% (${alertBombers}); launch ${inf.launchOnWarningMinutes} minutes after the first US launches are detected`, evidence: 'documented', provenance: { source: doc.bomberGroundAlert.source, method: 'Launch-on-warning timing inferred' } },
          { label: 'Non-alert bombers', value: nonAlertSurvive ? `Generate in ${inf.generationHours} hours and launch` : `Destroyed on the ground at H+${Math.round((struckAt ?? 0) / 60)} min, before they could generate`, evidence: 'inferred', provenance: { source: 'Coupling to the US strikes above', method: `A base is lost when a delivered US weapon lands within 30 km before ${inf.generationHours} hours` } },
        ],
      })
    }
    entities.push(...sovietSites)
    const sovietResult = allocate(sovietLaunchers, usTargets, { maxWeaponsPerTarget: 3, order: ['bomber'] })
    let sIndex = 0
    for (const s2 of sovietResult.sorties) {
      const l = sovietLaunchers.find((x) => x.id === s2.launcherId)!
      const t = usTargets.find((x) => x.id === s2.targetId)!
      const isAlert = sIndex % Math.max(1, Math.round(1 / alertFraction)) === 0
      const launch = isAlert ? l.reactionSeconds : inf.generationHours * 3_600
      const arrival = launch + s2.distanceMetres / (l.speedMs ?? 220)
      sIndex += 1
      const r = hash01Local(`sov:${s2.launcherId}:${s2.targetId}:${sIndex}`)
      const delivered = r < inf.usAirDefencePenetration.value
      sovietSummary.launched += 1
      if (delivered) sovietSummary.delivered += 1
      else sovietSummary.lost += 1
      const endFraction = delivered ? 1 : 0.7 + 0.28 * hash01Local(`sov-where:${sIndex}`)
      entities.push({
        kind: 'track',
        id: `sov-s-${sIndex}`,
        name: `${l.name} → ${t.name}`,
        designation: `SOVIET BOMBER · ${(s2.yieldKt / 1_000).toFixed(0)} MT ASSUMED${delivered ? '' : ' · LOST TO AIR DEFENCE'}`,
        label: false,
        side: 'defender',
        track: new Track([
          { position: l.position, time: launch },
          { position: delivered ? t.position : slerpTo(l.position, t.position, endFraction), time: launch + (arrival - launch) * endFraction },
        ]),
        reveal: 'progressive',
        evidence: 'inferred',
        provenance: { source: 'Soviet response', method: 'Force level documented, bases and targets inferred, US air-defence penetration one half assumed' },
        route: { evidence: 'reconstructed', provenance: { source: 'Great circle at cruise speed' } },
        facts: [],
      })
      if (!delivered) continue
      const existing = entities.find((x) => x.kind === 'effect' && x.id === `sov-e-${t.id}`)
      if (existing) continue
      entities.push({
        kind: 'effect',
        id: `sov-e-${t.id}`,
        name: t.name,
        designation: `SOVIET WEAPON · ${(s2.yieldKt / 1_000).toFixed(0)} MT ASSUMED`,
        label: false,
        compact: true,
        side: 'defender',
        center: t.position,
        time: arrival,
        effects: promptEffects(s2.yieldKt),
        burst: 'air',
        evidence: 'modelled',
        provenance: { source: BLAST_MODEL },
        facts: [
          { label: 'Target', value: t.id.startsWith('us-city') ? 'One of the ten largest US cities, 1960 census' : 'A SAC launch site of the order of battle', evidence: 'inferred', provenance: { source: 'Soviet targeting is not in the record' } },
          { label: 'Yield', value: `${(s2.yieldKt / 1_000).toFixed(0)} Mt`, evidence: 'inferred', provenance: { source: inf.bomberYieldKt.note } },
        ],
      })
    }
  }

  // Events: the documented sequence, and the waves as they leave.
  const byKind = (k: string) => result.sorties.filter((s) => s.kind === k).length
  events.push({ time: 0, text: `EXECUTION ORDER · OPTION ${option} · ${optionName} · ${result.weaponsAssigned.toLocaleString('en-GB')} WEAPONS ON ${result.targetsCovered.toLocaleString('en-GB')} TARGETS · UP TO ${weaponsPerTarget} PER TARGET · AIR POWER BATTLE FIRST (ALLOCATION INFERRED)` })
  if (option > 1) events.push({ time: 0.5, text: `${generation.hours} HOURS OF PREPARATION BEFORE H-HOUR · ${Math.round(generationAt(generation.hours).systems).toLocaleString('en-GB')} DELIVERY SYSTEMS READY (${generationAt(generation.hours).systemsEvidence.toUpperCase()}) · SAME TARGET LIST AS EVERY OPTION (DOCUMENTED)` })
  events.push({ time: 1, text: 'SEQUENCE: BALLISTIC MISSILES · FORWARD AREAS · CONUS FORCES (DOCUMENTED)' })
  events.push({ time: REACTION_FIXED, text: `H+15 MIN · FIXED BASES LAUNCH · ${byKind('icbm')} ICBM · ${byKind('irbm')} IRBM · ${byKind('bomber')} BOMBER AND THEATRE SORTIES` })
  events.push({ time: REACTION_SEA, text: `H+2 H · POLARIS ON STATION LAUNCH · ${byKind('slbm')} MISSILES` })
  events.push({ time: REACTION_FIXED + 1, text: `DELIVERY ASSURANCE ${Math.round(DOCUMENTED_ASSURANCE * 100)}% (DOCUMENTED AVERAGE) · ${delivered} DELIVERED · ${lostReliability} RELIABILITY LOSSES · ${lostPenetration} LOST IN PENETRATION (MODELLED)` })
  events.push({ time: soviet.inferred.launchOnWarningMinutes * 60, text: `SOVIET RESPONSE · ${Math.round(soviet.documented.bomberGroundAlert.value * 100)}% OF LONG RANGE AVIATION ON GROUND ALERT LAUNCHES ON WARNING (DOCUMENTED LEVEL, INFERRED TIMING) · ICBMs NOT ON ALERT, R-7 NEEDS 20 HOURS · SUBMARINES DAYS FROM LAUNCH RANGE` })
  events.push({ time: soviet.inferred.generationHours * 3_600, text: `SOVIET NON-ALERT BOMBERS GENERATE · ${sovietSummary.destroyedOnGround} DESTROYED ON THE GROUND BEFORE THEY COULD · ${sovietSummary.launched} SORTIES IN ALL · ${sovietSummary.delivered} PENETRATE (AIR DEFENCE ONE HALF, ASSUMED)` })
  const arrivals = Object.values(firstArrival).map((f) => f.time).sort((a, b) => a - b)
  if (arrivals.length) {
    events.push({ time: arrivals[0], text: 'FIRST DETONATION' })
    events.push({ time: arrivals[Math.floor(arrivals.length / 2)], text: 'HALF OF THE TARGETS STRUCK' })
    events.push({ time: arrivals[arrivals.length - 1], text: 'LAST DETONATION · OUTCOME CALCULATION COMPLETE WHEN THE SUM FINISHES' })
  }

  const summary: AlertForceSummary = {
    option,
    preparationHours: generation.hours,
    weaponsPerTarget,
    firstDetonation: arrivals[0] ?? 0,
    lastDetonation: arrivals[arrivals.length - 1] ?? 0,
    launchers: launchers.filter((l) => l.weapons > 0).length,
    weapons: result.weaponsAssigned,
    delivered,
    lostReliability,
    lostPenetration,
    penetration: calibration.penetration,
    sorties: result.sorties.length,
    targetsCovered: result.targetsCovered,
    airfieldsCovered: Object.keys(firstArrival).filter((id) => id.startsWith('a-')).length,
    complexesCovered: Object.keys(firstArrival).filter((id) => id.startsWith('t-')).length,
    megatons: megatons(result.sorties),
    alertFraction,
    bomberVehicles: Math.round(result.sorties.filter((s) => s.kind === 'bomber').length / 1.5),
  }

  const study: Study = {
    id: option === 1 ? 'siop62-alert' : `siop62-option-${option}`,
    title: option === 1 ? 'SIOP//62 · ALERT FORCE' : `SIOP//62 · OPTION ${option}`,
    subtitle: `Option ${option}${option === 1 ? '' : ` · ${generation.hours} hours of preparation`} · ${summary.weapons.toLocaleString('en-GB')} weapons from ${summary.launchers} launch sites to ${summary.airfieldsCovered} airfields and ${summary.complexesCovered} complexes · every assignment inferred`,
    variants: {
      label: 'Option',
      current: String(option),
      items: Array.from({ length: 14 }, (_, i) => ({ id: String(i + 1), label: String(i + 1), href: i === 0 ? '#/study/siop62-alert' : `#/study/siop62-alert/${i + 1}` })),
    },
    // The clock runs an hour past the last detonation, wherever the slowest bomber puts it.
    bounds: { start: -600, end: (Math.ceil(summary.lastDetonation / 3_600) + 1) * 3_600 },
    view: { center: [60, 62], zoom: 1.5 },
    populationGrid: 'popc_1961',
    exposureWorkers: 4,
    outcomeReference: { label: 'JCS estimate, 1961, alert force, Soviet dead', value: 80_000_000, source: `${EBB798.source}: 80 million, 37 percent of the population` },
    sides: {
      attacker: { name: 'United States' },
      defender: { name: 'Soviet response · United States dead', reference: { label: 'Pentagon civilians, 1961', value: 15_000_000, source: 'Kaplan via Sagan n. 47: two to fifteen million in a successful first strike; Ellsberg: the Air Force told Kennedy probably under ten million' } },
    },
    omissions: [
      'Every weapon-to-target assignment is an illustration by a stated rule; no assignment is in the record',
      'Bomber routing: great circles at cruise speed through the documented refuelling areas (Newfoundland, Alaska, Spain, Pacific), one hold each; tanker numbers and tracks beyond that are not modelled',
      `Attrition is statistical: ${ATTRITION_MODEL}; reliabilities ${Object.entries(RELIABILITY).map(([k, v]) => `${k} ${v.value} (${v.evidence})`).join(', ')}; bomber penetration solved as ${calibration.penetration.toFixed(2)}`,
      'Non-all-weather forces, 22 percent of the force carrying 16 percent of the weapons, had a further planning factor the briefing does not state',
      'US air defence against the Soviet response: no official estimate exists; one half assumed',
      'Soviet submarines and ICBMs: documented as unable to launch within the day; not drawn',
      'Airfields: a first-pass transcription reads about half of the 1,100 in the release; the Air Power Battle is under-represented by that much',
      option === 1 ? 'Yields: Mk-28 class assumed for bombers; the alert-force megatonnage check is on the readout' : `Yields: Mk-28 class assumed for every bomber weapon, which gives ${Math.round(summary.megatons).toLocaleString('en-GB')} Mt at this option; the documented ${GENERATED_MEGATONS.toLocaleString('en-GB')} Mt for the generated force implies the heavier Mk-36 and Mk-41 class weapons the non-alert bombers carried, which this enactment does not assign`,
      'Population exposure is per target with the largest weapon; overlapping targets are summed, so cities within reach of several targets are counted more than once',
      ...(option > 1 ? [`Generation is a straight line between the alert and fully generated tables, as the readiness lab draws it; the Soviet response is the tactical-warning one, and a Soviet force generated during the same ${generation.hours} hours of warning is not modelled`] : []),
    ],
    events,
    entities,
  }
  return { study, summary }
}

const built = new Map<number, ReturnType<typeof buildAlertForce>>()

/** The enactment for an execution option, built once and kept. */
export function forceForOption(option: number): ReturnType<typeof buildAlertForce> {
  const n = Math.max(1, Math.min(14, Math.round(option)))
  let f = built.get(n)
  if (!f) {
    f = buildAlertForce(n)
    built.set(n, f)
  }
  return f
}

export const ALERT_FORCE = forceForOption(1)

/** The generated force, option 14, read against Table 3. */
export const GENERATED_FORCE_DOCUMENTED = { weapons: 3_267, ballistic: 188, megatons: 7_420, provenance: GENERATION.provenance }

export interface OptionComparison {
  option: number
  hours: number
  weapons: number
  megatons: number
  targetsCovered: number
  weaponsPerTarget: number
  delivered: number
  firstDetonation: number
  lastDetonation: number
}

/** Every option side by side: the same targets, the same first and last detonation, more weapons on each. */
export function compareOptions(): OptionComparison[] {
  return Array.from({ length: 14 }, (_, i) => {
    const s = forceForOption(i + 1).summary
    return { option: s.option, hours: s.preparationHours, weapons: s.weapons, megatons: s.megatons, targetsCovered: s.targetsCovered, weaponsPerTarget: s.weaponsPerTarget, delivered: s.delivered, firstDetonation: s.firstDetonation, lastDetonation: s.lastDetonation }
  })
}

/** The documented figures the enactment should be read against. */
export const ALERT_FORCE_DOCUMENTED = {
  systems: 1_004,
  weapons: 1_685,
  megatons: 1_798,
  tableWeapons: 1_530,
  provenance: SAGAN,
}

export function alertForceCheck(): Array<{ label: string; enacted: string; documented: string }> {
  const s = ALERT_FORCE.summary
  const fmt = (v: number) => Math.round(v).toLocaleString('en-GB')
  return [
    { label: 'Weapons launched', enacted: fmt(s.weapons), documented: `${fmt(ALERT_FORCE_DOCUMENTED.weapons)} (briefing) · ${fmt(ALERT_FORCE_DOCUMENTED.tableWeapons)} (Table 1)` },
    { label: 'Megatons', enacted: fmt(s.megatons), documented: fmt(ALERT_FORCE_DOCUMENTED.megatons) },
    { label: 'Weapons delivered', enacted: `${fmt(s.delivered)} (${fmt(s.lostReliability)} reliability, ${fmt(s.lostPenetration)} penetration losses)`, documented: `assurance averaged ${Math.round(DOCUMENTED_ASSURANCE * 100)}% (JSTPS history); bomber penetration solved as ${s.penetration.toFixed(2)}` },
    { label: 'Targets covered', enacted: `${fmt(s.targetsCovered)} (${s.airfieldsCovered} airfields, ${s.complexesCovered} complexes)`, documented: '1,060 DGZs in the full plan, about 800 of them military; the alert force struck the highest-priority ones' },
    { label: 'Launch sites', enacted: fmt(s.launchers), documented: '112 bases in the plan' },
  ]
}
